[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = """
      default-src 'self';\
      style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com;\
      connect-src 'self' *.inaturalist.org;\
      img-src 'self' *.inaturalist.org https://inaturalist-open-data.s3.amazonaws.com;\
      font-src  https://fonts.gstatic.com"""

[[redirects]]
  from = "https://inaturalist-tools.netlify.app/*"
  to = "https://mobinat.org/:splat"
  status = 301
  force = true
